# Default Configuration: https://jekyllrb.com/docs/configuration/default/
# Font Matter Defaults:  https://jekyllrb.com/docs/configuration/front-matter-defaults/
# Configuration Options: https://jekyllrb.com/docs/configuration/options/

# Defaults for GitHub Pages
lsi: false
safe: true
source: . # your repo's top level directory
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

domain: aveline-art.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://aveline-art.github.io/  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /studious-lamp      # place folder name if the site is served in a subfolder

collections:
  authors:
    output: true
    
defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-sitemap


